# Generated by Django 5.2.12 on 2026-05-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='issue_type',
            field=models.CharField(choices=[('SERVICE', 'Service Issue'), ('ACADEMIC', 'Academic Issue')], default='SERVICE', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='priority_level',
            field=models.CharField(choices=[('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], default='LOW', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
