# Generated by Django 5.2.12 on 2026-05-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_issue_type_alter_category_priority_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_picture_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
