# Generated by Django 5.2.12 on 2026-06-04 03:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_options_permission_staffrole_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='resolutions/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ticket_resolution',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tickets/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ticket_attachment',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='meetingslot',
            name='meeting_slo_ticket__72cf89_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='message_ticket__c76d53_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='ticket_categor_60eb77_idx',
        ),
        migrations.RenameField(
            model_name='meetingslot',
            old_name='ticket_id',
            new_name='ticket',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='ticket_id',
            new_name='ticket',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='has_media',
        ),
        migrations.AddIndex(
            model_name='meetingslot',
            index=models.Index(fields=['ticket', 'start_time'], name='meeting_slo_ticket__d65cda_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['ticket', 'created_at'], name='message_ticket__3aafeb_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['category', '-created_at'], name='ticket_categor_1baf39_idx'),
        ),
        migrations.AddField(
            model_name='resolution',
            name='resolved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resolution',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='api.ticket'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.ticket'),
        ),
    ]
