# Generated by Django 5.2.12 on 2026-06-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_resolution_ticketattachment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='attachment_name',
        ),
    ]
