# Generated by Django 5.2.12 on 2026-06-08 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_user_message_sender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffrole',
            options={'ordering': ['-is_superadmin', 'name'], 'verbose_name': 'Admin Role', 'verbose_name_plural': 'Admin Roles'},
        ),
        migrations.RenameField(
            model_name='studentmeetingbooking',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='studentmeetingbooking',
            old_name='ticket_id',
            new_name='ticket',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='staff_role',
        ),
        migrations.AddField(
            model_name='meetingslot',
            name='campus_location',
            field=models.CharField(choices=[('MAIN', 'Main Campus'), ('EAS', 'EAS Campus')], default='MAIN', max_length=20),
        ),
        migrations.AddField(
            model_name='meetingslot',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='meetingslot',
            name='staff_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offered_meeting_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffrole',
            name='is_superadmin',
            field=models.BooleanField(default=False, help_text='If True, users with this role bypass all permission checks'),
        ),
        migrations.AlterField(
            model_name='meetingslot',
            name='meeting_type',
            field=models.CharField(choices=[('IN_PERSON', 'In Person Meeting'), ('ONLINE', 'Online Meeting')], default='ONLINE', max_length=20),
        ),
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the permission', max_length=250),
        ),
        migrations.AlterField(
            model_name='staffrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions granted to this role', related_name='roles', to='api.permission'),
        ),
    ]
