# Generated by Django 5.2.12 on 2026-06-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_message_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='If True, submitter identity is hidden from admins'),
        ),
    ]
