# Generated by Django 5.2.12 on 2026-06-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_ticket_is_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='public_ticket_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
