# Generated by Django 5.2.12 on 2026-06-14 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_ticket_public_ticket_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_notification_email', models.EmailField(help_text='The admin email address that receives new ticket notifications', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last admin who updated this setting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_setting_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Setting',
                'db_table': 'email_setting',
            },
        ),
    ]
