# Generated by Django 5.2.12 on 2026-06-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_profanityword'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='author_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
