# Generated by Django 5.0.4 on 2026-06-25 14:51

from django.db import migrations
from django.conf import settings
import hmac
import hashlib

def anonymize_existing_tickets(apps, schema_editor):
    Ticket = apps.get_model('api', 'Ticket')
    Message = apps.get_model('api', 'Message')
    
    # We need the real settings for ANONYMOUS_IDENTITY_KEY
    key = settings.ANONYMOUS_IDENTITY_KEY.encode('utf-8')

    # Find tickets that are anonymous but still have a submitted_by user attached
    for ticket in Ticket.objects.filter(is_anonymous=True, submitted_by__isnull=False):
        user_id = ticket.submitted_by_id
        
        # Generate hash
        msg = str(user_id).encode('utf-8')
        author_hash = hmac.new(key, msg, hashlib.sha256).hexdigest()
        
        ticket.author_hash = author_hash
        
        # Also fix messages sent by the user on this ticket
        Message.objects.filter(ticket=ticket, sender_id=user_id).update(sender=None)
        
        # Unlink user
        ticket.submitted_by = None
        ticket.save()

def reverse_anonymize(apps, schema_editor):
    # Reversing this is not fully possible because we lose the submitted_by info, 
    # but we can at least clear the author_hash
    Ticket = apps.get_model('api', 'Ticket')
    Ticket.objects.filter(author_hash__isnull=False).update(author_hash=None)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_ticket_author_hash'),
    ]

    operations = [
        migrations.RunPython(anonymize_existing_tickets, reverse_anonymize),
    ]
