# Generated by Django 5.2.12 on 2026-06-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20260625_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmeetingbooking',
            name='author_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
